version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile

    container_name: backend-app

    ports:
      - "7121:80"

    networks:
      - app-network

    volumes:
      - ./backend:/app
      - ./frontend:/app/static

    restart: unless-stopped

networks:
  app-network:
    driver: bridge